<?php

namespace Proxies\__CG__\uniJuegos\Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class juegos extends \uniJuegos\Bundle\Entity\juegos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'id', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'tituloJue', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'descJue', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'compJue', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'fotoJue', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'iconoJue', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'juecat', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'jueplat', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'juenots');
        }

        return array('__isInitialized__', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'id', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'tituloJue', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'descJue', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'compJue', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'fotoJue', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'iconoJue', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'juecat', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'jueplat', '' . "\0" . 'uniJuegos\\Bundle\\Entity\\juegos' . "\0" . 'juenots');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (juegos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTituloJue($tituloJue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTituloJue', array($tituloJue));

        return parent::setTituloJue($tituloJue);
    }

    /**
     * {@inheritDoc}
     */
    public function getTituloJue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTituloJue', array());

        return parent::getTituloJue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescJue($descJue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescJue', array($descJue));

        return parent::setDescJue($descJue);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescJue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescJue', array());

        return parent::getDescJue();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompJue($compJue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompJue', array($compJue));

        return parent::setCompJue($compJue);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompJue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompJue', array());

        return parent::getCompJue();
    }

    /**
     * {@inheritDoc}
     */
    public function setFotoJue($fotoJue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFotoJue', array($fotoJue));

        return parent::setFotoJue($fotoJue);
    }

    /**
     * {@inheritDoc}
     */
    public function getFotoJue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFotoJue', array());

        return parent::getFotoJue();
    }

    /**
     * {@inheritDoc}
     */
    public function setIconoJue($iconoJue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIconoJue', array($iconoJue));

        return parent::setIconoJue($iconoJue);
    }

    /**
     * {@inheritDoc}
     */
    public function getIconoJue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIconoJue', array());

        return parent::getIconoJue();
    }

    /**
     * {@inheritDoc}
     */
    public function setJuecat(\uniJuegos\Bundle\Entity\categorias $juecat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJuecat', array($juecat));

        return parent::setJuecat($juecat);
    }

    /**
     * {@inheritDoc}
     */
    public function getJuecat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJuecat', array());

        return parent::getJuecat();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addJueplat(\uniJuegos\Bundle\Entity\plataforma $jueplat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJueplat', array($jueplat));

        return parent::addJueplat($jueplat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJueplat(\uniJuegos\Bundle\Entity\plataforma $jueplat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJueplat', array($jueplat));

        return parent::removeJueplat($jueplat);
    }

    /**
     * {@inheritDoc}
     */
    public function getJueplat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJueplat', array());

        return parent::getJueplat();
    }

    /**
     * {@inheritDoc}
     */
    public function addJuenot(\uniJuegos\Bundle\Entity\noticias $juenots)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJuenot', array($juenots));

        return parent::addJuenot($juenots);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJuenot(\uniJuegos\Bundle\Entity\noticias $juenots)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJuenot', array($juenots));

        return parent::removeJuenot($juenots);
    }

    /**
     * {@inheritDoc}
     */
    public function getJuenots()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJuenots', array());

        return parent::getJuenots();
    }

}
