noticias_new:
    path:     /new
    defaults: { _controller: "uniJuegosBundle:noticias:new" }

noticias_create:
    path:     /create
    defaults: { _controller: "uniJuegosBundle:noticias:create" }
    requirements: { _method: post }

noticias_edit:
    path:     /{id}/edit
    defaults: { _controller: "uniJuegosBundle:noticias:edit" }

noticias_update:
    path:     /{id}/update
    defaults: { _controller: "uniJuegosBundle:noticias:update" }
    requirements: { _method: post|put }

noticias_delete:
    path:     /{id}/delete
    defaults: { _controller: "uniJuegosBundle:noticias:delete" }
    requirements: { _method: post|delete }