categorias:
    path:     /
    defaults: { _controller: "uniJuegosBundle:categorias:index" }

categorias_show:
    path:     /{id}/show
    defaults: { _controller: "uniJuegosBundle:categorias:show" }


uni_juegos_categorias:
    resource: "@uniJuegosBundle/Resources/config/routing/conSeguridad/categoriasSeguridad.yml"
    prefix:   /conSeguridad