juegos:
    path:     /
    defaults: { _controller: "uniJuegosBundle:juegos:index" }

juegos_show:
    path:     /{id}/show
    defaults: { _controller: "uniJuegosBundle:juegos:show" }


juegos_buscar_juego:
    path:     /buscarjuego
    defaults: { _controller: "uniJuegosBundle:juegos:buscarJuego" }
    
juegos_responder_juego:
    path:     /responderjuego
    defaults: { _controller: "uniJuegosBundle:juegos:responderJuego" }
    requirements: { _method: post|put }
uni_juegos_juegos:
    resource: "@uniJuegosBundle/Resources/config/routing/conSeguridad/juegosSeguridad.yml"
    prefix:   /conSeguridad