juegos:
    path:     /
    defaults: { _controller: "uniJuegosBundle:juegos:index" }

juegos_show:
    path:     /{id}/show
    defaults: { _controller: "uniJuegosBundle:juegos:show" }

juegos_new:
    path:     /new
    defaults: { _controller: "uniJuegosBundle:juegos:new" }

juegos_create:
    path:     /create
    defaults: { _controller: "uniJuegosBundle:juegos:create" }
    requirements: { _method: post }

juegos_edit:
    path:     /{id}/edit
    defaults: { _controller: "uniJuegosBundle:juegos:edit" }

juegos_update:
    path:     /{id}/update
    defaults: { _controller: "uniJuegosBundle:juegos:update" }
    requirements: { _method: post|put }

juegos_delete:
    path:     /{id}/delete
    defaults: { _controller: "uniJuegosBundle:juegos:delete" }
    requirements: { _method: post|delete }
