noticias:
    path:     /
    defaults: { _controller: "uniJuegosBundle:noticias:index" }

noticias_show:
    path:     /{id}/show
    defaults: { _controller: "uniJuegosBundle:noticias:show" }


uni_juegos_noticias:
    resource: "@uniJuegosBundle/Resources/config/routing/conSeguridad/noticiasSeguridad.yml"
    prefix:   /conSeguridad