plataforma:
    path:     /
    defaults: { _controller: "uniJuegosBundle:plataforma:index" }

plataforma_show:
    path:     /{id}/show
    defaults: { _controller: "uniJuegosBundle:plataforma:show" }


uni_juegos_plataforma:
    resource: "@uniJuegosBundle/Resources/config/routing/conSeguridad/plataformaSeguridad.yml"
    prefix:   /conSeguridad